  
version: 0.2
phases:
  build:
    commands:
      - yarn
      - yarn build
  post_build:
    commands:
      - echo Build completed on $(date +%d-%m-%Y_%H-%M-%S)
      - ls -al
artifacts:
  files:
    - "**/*"
  name: build-output