  
version: 0.2
phases:
  build:
    commands:
      - dockerImageName=$ECR_REPO/nextjs:$CODEBUILD_BUILD_NUMBER
      - docker build -t $dockerImageName .
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $ECR_REPO
      - docker push $dockerImageName
      - sed -e "s|\${imageName}|$dockerImageName|" Dockerrun.aws.json.template > Dockerrun.aws.json
      - cat Dockerrun.aws.json
  post_build:
    commands:
      - echo Build completed on $(date +%d-%m-%Y_%H-%M-%S)
      - ls -al
artifacts:
  files:
    - 'Dockerrun.aws.json'
  name: builds/$CODEBUILD_BUILD_NUMBER/my-artifacts