  
version: 0.2
phases:
  build:
    commands:
      - yarn 
      - yarn build
      - yarn prune --production
  post_build:
    commands:
      - echo Build completed on $(date +%d-%m-%Y_%H-%M-%S)
artifacts:
  files:
    - '**/*'
  